// GET PRODUCTS
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";

// GET PRODUCT

export const OBTENER_UNICO_PRODUCTO = "OBTENER_UNICO_PRODUCTO";
export const OBTENER_UNICO_PRODUCTO_EXITO = "OBTENER_UNICO_PRODUCTO_EXITO";
export const OBTENER_UNICO_PRODUCTO_ERROR = "OBTENER_UNICO_PRODUCTO_ERROR";

// POST PRODUCT
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

// PUT PRODUCT
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTOS";
export const EDITAR_PRODUCTO_EXITO = "EDITAR_PRODUCTOS_EXITO";
export const EDITAR_PRODUCTO_ERROR = "EDITAR_PRODUCTOS_ERROR";

// DELETE PRODUCT
export const BORRAR_PRODUCTO = "BORRAR_PRODUCTO";
export const BORRAR_PRODUCTO_EXITO = "BORRAR_PRODUCTO_EXITO";
export const BORRAR_PRODUCTO_ERROR = "BORRAR_PRODUCTO_ERROR";

// FORM VALIDATOR STATE
export const MOSTRAR_ALERTA_FORMULARIO = "MOSTRAR_ALERTA_FORMULARIO"
export const OCULTAR_ALERTA_FORMULARIO = "OCULTAR_ALERTA_FORMULARIO"


